// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhhlrcdtipjnvmpmjqdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoaGxyY2R0aXBqbnZtcG1qcWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5OTY5MTUsImV4cCI6MjA1ODU3MjkxNX0.aFCrIW6zzJWEeF2IS8zTIck2wEuCpCp_5zWECZt6JvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);